# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('data_id', models.IntegerField(default=1)),
                ('label', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('last_code', models.CharField(default='', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
