# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-13 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('change_time', models.DateTimeField(auto_now=True)),
                ('change_code', models.CharField(default='', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
                ('icon', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
