# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marknode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('change_code', models.CharField(default='', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=20)),
                ('goal', models.CharField(default="{'x':0.0, 'y':0.0, 'z': 0.0}", max_length=100)),
                ('is_delay', models.BooleanField(default=False)),
                ('delay_time', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('evaluate', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='robot',
            name='charge',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='robot',
            name='on_mission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Robot'),
        ),
    ]
