# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170213_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marknode',
            old_name='z',
            new_name='rz',
        ),
        migrations.AlterField(
            model_name='mission',
            name='goal',
            field=models.CharField(default="{'x':0.0, 'y':0.0, 'rz': 0.0}", max_length=100),
        ),
    ]
